model_dir: results/training/20260330_161209_segmenter_50_epochs_playground_no_lbl_smoothing
data_dir: results/training/20260330_161209_segmenter_50_epochs_playground_no_lbl_smoothing/logs/best_preds/images
save_mask_as_img: True