train:
  output_dir: "results/training"  # where to save resulting model
  output_suffixe: playground_no_lbl_smoothing # what suffixe for the resulting folder (data and time will be automatically added in name to avoid overrights)
  val_split: 0.1  # which fraction of the dataset is used for the validation (the rest will go for training set)
  frac_data: 1.0  # how much of the dataset will be used in total (mostly used in developing phase)
  num_epochs: 50  # number of time the full dataset is passed through the training loop
  batch_size: 8 # number of samples loaded at the same time in the VRAM
  num_workers: 4 # how many CPU processes are used by the DataLoader to prepare the batches
  learning_rate: 5e-5 # has been finetuned. do not touch
  weight_decay: 0.01  # has been finetuned. do not touch
  label_smoothing: 0.0  # if you want to use label smoothing, change for a greater value than 0 (e.g. 1e-3, 0.01, 0.1)
  loss_weights: [1,5] # how much weight is given to respectively the background and the playgrounds. Compensate for classes imbalance
  from_pretrain: False  # if training from a pretrained model (e.g. the one already present in the repo)
  pretrain_dir: models/segmenter_playground # the path to the pretrained model's directory
  resume_from_existing: False # if the training is canceled early, it can be resumed here
  existing_dir: results/training/failed_training # path to the failed training
  do_data_augmentation: True  # to process flipping and rotation of the samples during training phase (recommanded!)
  do_da_scaling: False  # to process random scaling of the samples during training phase (not recommanded. multiple resolutions of the samples are already prepared during the preprocessing phase)
  do_save_best_preds: True  # if the best predictions of the validation set are to be saved (will appear in logs\best_preds)
  base_model: nvidia/segformer-b0-finetuned-ade-512-512 # if not training from a pretrained model, here is the name of the model retrieved from the web (list of available models under)
dataset:
  mode: auto # choose 'auto' for dataset splitted automatically or 'split' for training and validation sets already separated manualy 
  dataset_dir: data/dataset_segmentation_playground   # if using mode 'auto'
  trainset_dir: data/splitset_Bern_v2_training        # if using mode 'split'
  valset_dir: data/splitset_Bern_v2_validation        # if using mode 'split'


  # list of pretrained models:
  # nvidia/segformer-b0-finetuned-ade-512-512
  # nvidia/segformer-b0-finetuned-cityscapes-1024-1024
  # nvidia/segformer-b0-finetuned-cityscapes-512-1024
  # nvidia/segformer-b0-finetuned-cityscapes-640-1280
  # nvidia/segformer-b0-finetuned-cityscapes-768-768
  # nvidia/segformer-b1-finetuned-ade-512-512
  # nvidia/segformer-b1-finetuned-cityscapes-1024-1024
  # lsi55/ddpm-ema-nvidia-segformer-b1-finetuned-cityscapes-1024-1024
  # nvidia/segformer-b2-finetuned-cityscapes-1024-1024
  # nvidia/segformer-b2-finetuned-ade-512-512
  # nvidia/segformer-b3-finetuned-ade-512-512
  # nvidia/segformer-b3-finetuned-cityscapes-1024-1024
  # nvidia/segformer-b4-finetuned-ade-512-512
  # nvidia/segformer-b4-finetuned-cityscapes-1024-1024
  # nvidia/segformer-b5-finetuned-ade-640-640
  # nvidia/segformer-b5-finetuned-cityscapes-1024-1024
  # janakipanneerselvam/SegFormer_Sunlit_nvidia_mit-b5
  # janakipanneerselvam/SegFormer_Sunlit_nvidia_mit-b5_v2
  # janakipanneerselvam/SegFormer_Sunlit_nvidia_mit-b5_Almonds
  # janakipanneerselvam/Almond_SegFormer_Sunlit_nvidia_mit-b5

